### PR TITLE
Only add trait (not lifetime) bounds from methods to `T` (and update tests)

### LINKED ISSUE #65: Unable to use auto_impl with async-trait
I was trying to use `auto_impl` to delegate the implementation of `Box<T> where T: Trait` and `Trait` was a trait annotated with the [`async-trait`](https://github.com/dtolnay/async-trait) procedural macro. I was using it like this:

```rust
#[async_trait]
#[auto_impl(Box)]
trait Foo: Sync {
    async fn bar(&self) -> Result<u32, Error>;
}
```

The ordering of the above macros matters, as it ensures that `async_trait` transforms `Foo` into the following Rust code before `auto_impl` parses it:

```rust
#[auto_impl(Box)]
trait Foo: Sync {
    fn bar<'life0, 'async_trait>(
        &'life0 self
    ) -> Pin<Box<dyn Future<Output = Result<u32, Error>> + Send + 'async_trait>> where
        'life0: 'async_trait,
        Self: 'async_trait;
}
```

Provided that the `Sync` bound shown above is present as a supertrait of `Foo`, the above code should be object safe. I expected `#[auto_impl(Box)]` to emit the following implementation:

```rust
impl<T: Foo + ?Sized> Foo for Box<T>
where
    Box<T>: Sync
```

However, it emitted the following implementation instead:

```rust
impl<T: Foo> Foo for Box<T>
where
    Box<T>: Sync
```

This meant that the following code was able to compile with a manual `Box` implementation but failed under the `auto_impl`-generated implementation:

```rust
fn assert_impl<T: Foo>() {}

fn foo() {
    assert_impl::<Box<dyn Foo>>(); // ERROR: Not object safe with `auto_impl`
}
```

Do you have an idea as to why the `?Sized` bound was not applied in this case?

See https://github.com/ebkalderon/tower-lsp/pull/109 for the original pull request that inspired this issue.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #65

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
@KodrAus in case you find some time to take a look, [this comment](https://github.com/auto-impl-rs/auto_impl/issues/65#issuecomment-647035827) has another explanation for this change. If you don't have time, don't worry. I would try to release this and all the other stuff as 0.4 soon after merging. 

(Oh and, congratulations from me too :wink:)

**Comment by LukasKalbertodt** [comment]
No worries about not having time to review. But I will just merge this now :)

**Comment by ebkalderon** [comment]
Thanks for all the good work, @LukasKalbertodt!

**Comment by LukasKalbertodt** [comment]
@ebkalderon This should also now be released as 0.4.0.

**Pull request merged**
