### PR TITLE
inherit attributes for generated methods / consts / types

### PR DESCRIPTION
**Pull request by bachue**

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
Thanks for the PR! Can you briefly describe your motivation for this change? In particular, what kind of attributes would you like to inherit? The change looks good to me and makes sense on first thought, but I'm worried we are missing some attributes that do not make sense to "inherit" in the generated impls.

**Comment by bachue** [comment]
@LukasKalbertodt Ok, in my case, I want to inherit `cfg(feature = "xxx")` and `cfg_attr(feature = "docs", doc(cfg(feature = "xxx")))` attribtues, both of them are used for conditional compilation. Because for my traits, some interfaces are only available when the specified feature is on.

**Comment by LukasKalbertodt** [comment]
For `cfg`, I'm convinced I think. I don't see how this could backfire and I think one always wants to also apply this to the generated items. However, other attributes I'm not sure sure. 

You use `doc` in `cfg_attr`, but does this really need to apply to the generated item as well? And `doc` attributes, like `doc(hidden)` or the simple `doc = "comment..."` I don't see why they would apply to the generated item as well. Further, we have `allow`, `warn`, `forbid`, `deprecated`, `must_use` and tool attributes (e.g. `rustfmt::skip`). I don't think all of those should always apply to the generated item. 

So I don't think I want to accept the PR as is. If you restrict it to `cfg` attributes, that should be fine, I guess. Also, note that this crate is for the 90% of cases and doesn't aim to work for every possible use case. Because the latter would come at the cost of an increase in complexity.

**Comment by bachue** [comment]
@LukasKalbertodt Thanks, PR is updated

**Comment by LukasKalbertodt** [comment]
@bachue I'm not really maintaining this crate anymore, I'm sorry. @KodrAus might take this from here!

**Comment by KodrAus** [comment]
Thanks for the PR @bachue

It's been a while since I've been through this crate, but this seems reasonable to me. I'll merge this in and take stock of things and look at getting another release out :bow:

**Pull request merged**
